added cancels to the menus
CS3250-IllegalSkillsException/myDatabase pull request #85
Opened 2021-04-04 18:43 UTC by meddy7

Added cancels to the menu

2021-04-04 19:30 UTC, mesta88 requested changes
Looks great! Just found one thing while testing. In users table, "3. Exit Menu" is on the same line and connected to 2. Find User Email. Just needs a \n in between.

2021-04-04 19:34 UTC, meddy7 commented
Added the \n

2021-04-04 19:36 UTC, mesta88 approved these changes

2021-04-05 01:04 UTC, jfelici4 approved these changes
I was able to exit out of the three table menus without issue. Approved.

2021-04-05 02:36 UTC, flip1012 approved these changes

2021-04-05 02:40 UTC, merged